# Generated by Django 4.1 on 2022-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestos',
            name='mail',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='monotributista',
            name='mail',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='responsableinscripto',
            name='mail',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
    ]
