# Generated by Django 4.1 on 2022-09-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0002_alter_impuestos_mail_alter_monotributista_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monotributista',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
